CREATE_APPLICATION = 'create_application'
DELETE_APPLICATION = 'delete_application'
MAIN_MENU = 'main_menu'
INSERT_DATA = 'insert_query'
DELETE_ENTRY = 'deletion_confirmation'
DELETE_COLUMN = 'delete_column'
CANCEL_COLUMN_DELETION = 'cancel_deletion'
